---
language: python
sudo: false
cache: pip
matrix:
  allow_failures:
    - python: nightly
    - env: DJANGO="https://github.com/django/django/archive/main.tar.gz"
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "nightly"
env:
  - DJANGO="Django>=2.2,<2.3"
  - DJANGO="Django>=3.1,<3.2"
  - DJANGO="Django>=3.2,<3.3"
  - DJANGO="https://github.com/django/django/archive/main.tar.gz"
before_install:
  - pip install --quiet codecov
install:
  - pip install --quiet --pre $DJANGO
  - python setup.py -q install
script:
  - coverage run setup.py -v test
after_success:
  - codecov
